version: '3.8'

services:
  db:
    image: 'postgres:14.1-alpine'
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/nestjs
    ports:
      - '5432:5432'
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@postgres.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - postgres-network
volumes:
  db:
    driver: local

networks: 
  postgres-network:
    driver: bridge